#----------------------------------------------------------------------------
# file:
#	Top-dir Makefile.am for SDP Toolkit
#
# author:
#	Matthew Yun / Raytheon 
#
# history:
#	5-Aug-2013 Initial version
#
# notes:
# 	The src directory contains all the source files and the Makefiles to 
#	create the toolkit library. The utils directory only contains the 
#	Makefiles needed to create the toolkit utilities. It is important that 
#	the libraries are built before the utilities, since the utilities 
#	depend on the library.
#----------------------------------------------------------------------------

SUBDIRS = utils/SMF message src utils
