#-----------------------------------------------------------------------------
# file:		makefile for XML tools 
#		(for MET only)
#
# environment:	MPPDE, machine-independent, PGS directory structure
# 	
# environment variables dependencies:
#   compiler:  CC
#   includes:  PGSINC
#   libraries: PGSLIB
#   other:     PGSBIN PGSSRC HDFSYS
#  
# author: Abe Taaheri / Raytheon
#
# history:
#	01-May-2009 AT  Initial version
#
# notes:
# 	1) This file is intended for use in the Multi-Platform PGS Development
# 	   Environment (MPPDE) .  It depends on the PGS-defined toolkit 
# 	   directory structure, and on environmental variables defined
# 	   by MPPDE startup files.  This is how machine independence
# 	   is maintained.
# 	2) Target executable files are moved to $PGSBIN
# 	3) Target object files are moved to $(PGSLIB)/obj/XML
# 	4) To build the PGS CUC tools library, type 'make lib'
#	   (This runs the script $PGSBIN/mkpgslib to build the library).
#----------------------------------------------------------------------------

#
# set the name of this tool group
#
GRP = XML

# define sh shell (needed for embedded shell scripts)
SHELL=/bin/sh


# Default target
TARG=all

# name of remove utility
RM = /bin/rm
RMFLAGS = -f 

# note: some xml compilations with g++ results in error. Therefore
# below we use MFLAGS insstead of MFLAGS2 at the end of os_type
# This will compile XML files with gcc instaed og g++
MFLAGS2 = -f Makefile.cpp_ofunix

CFLAG1 =

# define optimization level for comilation
OPT_LEVEL = -O

# define C preprocessor symbols 
DFLAGS  = -DSUN_UNIX

# path for #include directive
IFLAG   = -I. $(ECS_TOOLKIT_INCLUDES) -I$(PGSINC) -I$(PGSINC)/libxml

# object files from this sub-group needed to build library  

LIBOFILES = \
	$(PGSCPPO)/$(GRP)/SAX.o \
	$(PGSCPPO)/$(GRP)/entities.o \
	$(PGSCPPO)/$(GRP)/encoding.o \
	$(PGSCPPO)/$(GRP)/error.o \
	$(PGSCPPO)/$(GRP)/parserInternals.o \
	$(PGSCPPO)/$(GRP)/parser.o \
	$(PGSCPPO)/$(GRP)/tree.o \
	$(PGSCPPO)/$(GRP)/hash.o \
	$(PGSCPPO)/$(GRP)/list.o \
	$(PGSCPPO)/$(GRP)/xmlIO.o \
	$(PGSCPPO)/$(GRP)/xmlmemory.o \
	$(PGSCPPO)/$(GRP)/uri.o \
	$(PGSCPPO)/$(GRP)/valid.o \
	$(PGSCPPO)/$(GRP)/xlink.o \
	$(PGSCPPO)/$(GRP)/HTMLparser.o \
	$(PGSCPPO)/$(GRP)/HTMLtree.o \
	$(PGSCPPO)/$(GRP)/debugXML.o \
	$(PGSCPPO)/$(GRP)/xpath.o \
	$(PGSCPPO)/$(GRP)/xpointer.o \
	$(PGSCPPO)/$(GRP)/xinclude.o \
	$(PGSCPPO)/$(GRP)/nanohttp.o \
	$(PGSCPPO)/$(GRP)/nanoftp.o \
	$(PGSCPPO)/$(GRP)/DOCBparser.o \
	$(PGSCPPO)/$(GRP)/catalog.o \
	$(PGSCPPO)/$(GRP)/globals.o \
	$(PGSCPPO)/$(GRP)/threads.o \
	$(PGSCPPO)/$(GRP)/c14n.o \
	$(PGSCPPO)/$(GRP)/xmlstring.o \
	$(PGSCPPO)/$(GRP)/xmlregexp.o \
	$(PGSCPPO)/$(GRP)/xmlschemas.o \
	$(PGSCPPO)/$(GRP)/xmlschemastypes.o \
	$(PGSCPPO)/$(GRP)/xmlunicode.o \
	$(PGSCPPO)/$(GRP)/xmlreader.o \
	$(PGSCPPO)/$(GRP)/relaxng.o \
	$(PGSCPPO)/$(GRP)/dict.o \
	$(PGSCPPO)/$(GRP)/SAX2.o \
	$(PGSCPPO)/$(GRP)/xmlwriter.o \
	$(PGSCPPO)/$(GRP)/legacy.o \
	$(PGSCPPO)/$(GRP)/chvalid.o \
	$(PGSCPPO)/$(GRP)/pattern.o \
	$(PGSCPPO)/$(GRP)/xmlsave.o \
	$(PGSCPPO)/$(GRP)/xmlmodule.o \
	$(PGSCPPO)/$(GRP)/schematron.o

#
# targets
#

all:	message os_type

os_type:
	@cflag=$(CFLAG1);					\
	if [ $(BRAND) = "hp" ] ; then 				\
	    cflag="-Ae" ;					\
	    echo "Compiling on HP.  NOTE: FLAG added." ;	\
	fi ;							\
	if [ $(BRAND) = "linux" ] ; then 			\
	    cflag="-DLINUX" ;					\
	    echo "Compiling on LINUX.  NOTE: FLAG added." ;	\
	fi ;							\
	if [ $(BRAND) = "linux64" ] ; then 			\
	    cflag="-DLINUX64" ;					\
	    echo "Compiling on LINUX64.  NOTE: FLAG added." ;	\
	fi ;							\
	if [ $(BRAND) = "linux32" ] ; then 			\
	    cflag="-DLINUX" ;					\
	    echo "Compiling on LINUX32.  NOTE: FLAG added." ;	\
	fi ;							\
        if [ $(BRAND) = "macintosh" ] ; then                        	\
            cflag="-DMACINTOSH" ;                                   	\
            echo "Compiling on Macintosh.  NOTE: FLAG added." ;     	\
        fi ;                        	                 	    	\
        if [ $(BRAND) = "macintel" ] ; then            	    		\
            cflag="-DMACINTEL" ;                                   	\
            echo "Compiling on Macintosh (Intel).  NOTE: FLAG added." ; \
        fi ;                                             		\
        if [ $(BRAND) = "cygwin" ] ; then            	    		\
            cflag="-DCYGWIN" ;                                   	\
            echo "Compiling on Cygwin.  NOTE: FLAG added." ; 		\
        fi ;                        	                 	    	\
	$(MAKE) $(MFLAGS2) all2 CFLAG1="$$cflag"

all2: $(PGSLIB)/libPGSTKcpp.a

$(PGSLIB)/libPGSTKcpp.a: $(LIBOFILES)
	@$(PGSBIN)/mkpgslib.cpp $(GRP)

dbug:
	@$(MAKE) OPT_LEVEL=-g $(TARG)

lib:
	@${PGSBIN}/mkpgslib.cpp $(GRP)

message:
	@echo " Makefile.cpp_ofunix for group: $(GRP); Target: all"

clean:
	$(RM) $(RMFLAGS) core *.o $(LIBOFILES) $(PGSCPPO)/$(GRP)/*.o

#
# compilation rules

$(PGSCPPO)/$(GRP)/SAX.o: SAX.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/entities.o: entities.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/encoding.o: encoding.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/error.o: error.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/parserInternals.o: parserInternals.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/parser.o: parser.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/tree.o: tree.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/hash.o: hash.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/list.o: list.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlIO.o: xmlIO.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlmemory.o: xmlmemory.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/uri.o: uri.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/valid.o: valid.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xlink.o: xlink.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/HTMLparser.o: HTMLparser.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/HTMLtree.o: HTMLtree.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/debugXML.o: debugXML.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xpath.o: xpath.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xpointer.o: xpointer.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xinclude.o: xinclude.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/nanohttp.o: nanohttp.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/nanoftp.o: nanoftp.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/DOCBparser.o: DOCBparser.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/catalog.o: catalog.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/globals.o: globals.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/threads.o: threads.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/c14n.o: c14n.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlstring.o: xmlstring.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlregexp.o: xmlregexp.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlschemas.o: xmlschemas.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlschemastypes.o: xmlschemastypes.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlunicode.o: xmlunicode.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlreader.o: xmlreader.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/relaxng.o: relaxng.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/dict.o: dict.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/SAX2.o: SAX2.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlwriter.o: xmlwriter.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/legacy.o: legacy.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/chvalid.o: chvalid.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/pattern.o: pattern.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlsave.o: xmlsave.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/xmlmodule.o: xmlmodule.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@
$(PGSCPPO)/$(GRP)/schematron.o: schematron.c
	$(CC) -c $(CFLAG1) $(OPT_LEVEL) $(DFLAGS) $(IFLAG) $? -o $@


# force the default make rule to search for a specific make rule
# for a given input file (i.e. target)
.c.o:
	$(MAKE) $(MFLAGS) $(MFLAGS2) $(PGSCPPO)/$(GRP)/$@
