#----------------------------------------------------------------------------
# file:
#	Makefile.am for SDP Toolkit GCT freeware sub group
#
# author:
#	Matthew Yun / Raytheon 
#
# history:
#	5-Aug-2013 Initial version
#
# notes:
#
#----------------------------------------------------------------------------

GRP = GCT

# define sh shell (needed for embedded shell scripts)
SHELL=/bin/sh

# Name of the remove utility and flags
RM= /bin/rm
RMFLAGS= -f

# Path for 'include' directive
CPPFLAGS = -I$(top_srcdir)/include -I$(top_srcdir)/include/FW

# Source files from this subgroup needed to build the library
noinst_LTLIBRARIES = libgctfreeware.la

libgctfreeware_la_CFLAGS = -DPGS_TOOLKIT_COMPILE

# List source files here
libgctfreeware_la_SOURCES = \
	alberfor.c \
	alberinv.c \
	alconfor.c \
	alconinv.c \
	azimfor.c \
	aziminv.c \
	bceafor.c \
	bceainv.c \
	ceafor.c \
	ceainv.c \
	cproj.c \
	eqconfor.c \
	eqconinv.c \
	equifor.c \
	equiinv.c \
	gnomfor.c \
	gnominv.c \
	goodfor.c \
	goodinv.c \
	gvnspfor.c \
	gvnspinv.c \
	hamfor.c \
	haminv.c \
	imolwfor.c \
	imolwinv.c \
	lamazfor.c \
	lamazinv.c  \
	lamccfor.c \
	lamccinv.c \
	merfor.c \
	merinv.c \
	millfor.c \
	millinv.c \
	molwfor.c \
	molwinv.c \
	obleqfor.c \
	obleqinv.c \
	omerfor.c \
	omerinv.c \
	orthfor.c \
	orthinv.c \
	paksz.c \
	polyfor.c \
	polyinv.c \
	psfor.c \
	psinv.c \
	report.c \
	robfor.c \
	robinv.c \
	sinfor.c \
	sininv.c \
	somfor.c \
	sominv.c \
	sphdz.c \
	sterfor.c \
	sterinv.c \
	stplnfor.c \
	stplninv.c \
	tmfor.c \
	tminv.c \
	untfz.c \
	vandgfor.c \
	vandginv.c \
	wivfor.c \
	wivinv.c\
	wviifor.c \
	wviiinv.c \
	isinusfor.c \
	isinusinv.c \
	utmfor.c \
	utminv.c
